apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: tobiaskohlbau/debug
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "sleep 90000"]
